COMPONENT="software-app-b"

.PHONY: build test lint doc release

build:
	@echo "building $(COMPONENT)"
	@mkdir target

test:
	@echo "testing $(COMPONENT)"

lint:
	@echo "linting $(COMPONENT)"

doc:
	@echo "documenting $(COMPONENT)"
	@mkdir docs

release:
	@echo "releasing $(COMPONENT)"
